// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW4AR_hajYdyrjJ7skBuld6vUK1d5bA7o',
    appId: '1:663685160278:web:736e75f750fa9397d2caf7',
    messagingSenderId: '663685160278',
    projectId: 'sbsprototype',
    authDomain: 'sbsprototype.firebaseapp.com',
    storageBucket: 'sbsprototype.appspot.com',
    measurementId: 'G-W2TE18SBHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYnlQM4nhuZK_x6OiRXXrDt6gPupLZ-4',
    appId: '1:663685160278:android:19ed1be24d3943ccd2caf7',
    messagingSenderId: '663685160278',
    projectId: 'sbsprototype',
    storageBucket: 'sbsprototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcApWt-EHZpS8T8Kk-6RdItOK-jdbw3Iw',
    appId: '1:663685160278:ios:967f6414efacd2ead2caf7',
    messagingSenderId: '663685160278',
    projectId: 'sbsprototype',
    storageBucket: 'sbsprototype.appspot.com',
    iosBundleId: 'com.example.sbsPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcApWt-EHZpS8T8Kk-6RdItOK-jdbw3Iw',
    appId: '1:663685160278:ios:967f6414efacd2ead2caf7',
    messagingSenderId: '663685160278',
    projectId: 'sbsprototype',
    storageBucket: 'sbsprototype.appspot.com',
    iosBundleId: 'com.example.sbsPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW4AR_hajYdyrjJ7skBuld6vUK1d5bA7o',
    appId: '1:663685160278:web:ed8ae64f727417f3d2caf7',
    messagingSenderId: '663685160278',
    projectId: 'sbsprototype',
    authDomain: 'sbsprototype.firebaseapp.com',
    storageBucket: 'sbsprototype.appspot.com',
    measurementId: 'G-JZTRECJ9HC',
  );
}
